name = "tjsb-webpage"
main = "backend/worker.js"
compatibility_date = "2024-05-01"
pages_build_output_dir = "dist"

[assets]
directory = "dist"

[[d1_databases]]
binding = "DB"
database_name = "tjsb_eshop"
database_id = "5f0c7ff3-45c6-4195-8049-e9151135cfaf"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tjsb-eshop"

[vars]
ENVIRONMENT = "production"
ENABLE_EMAILS = "true"
TEAM_DOMAIN="tjsbfotbal.cloudflareaccess.com"
SENDER_EMAIL="rezervace@tjsbfotbal.cz"
SENDER_NAME="rezervace@tjsbfotbal.cz"
REPLY_TO_EMAIL="noreply@tjsbfotbal.cz"
REPLY_TO_NAME="Neodpovídejte / Automat"

[triggers]
crons = ["0 3 * * *"]