export const OrderStatus = {
    PENDING: 'PENDING',
    READY: 'READY',
    COMPLETED: 'COMPLETED',
    CANCELED: 'CANCELED',
    CANCELED_BY_USER: 'CANCELED_BY_USER',
    CANCELED_UNCOLLECTED: 'CANCELED_UNCOLLECTED',
};
